#!/usr/bin/env python


import serial
import time


ser = serial.Serial(
	port='/dev/cu.usbmodemMDC2XXX1',
	baudrate = 115200,
	parity=serial.PARITY_NONE,
	stopbits=serial.STOPBITS_ONE,
	bytesize=serial.EIGHTBITS,
	timeout=1
	)
throttleVar = 0
steeringVar = 1
throttle = 300
steering = 0
counter = 0

while 1:
	#ser.write('!VAR %d %d\r'%(throttleVar, throttle))
	#ser.write('!VAR %d %d\r'%(steeringVar, steering))
	ser.write('!VAR %d %d\r'%(throttleVar, throttle))
	time.sleep(1)
	print(throttle)
	throttle = -throttle
